version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.yaml
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/univesp
      - SECRET_KEY=dev-secret-key-change-in-production
      - FLASK_APP=run.py
      - FLASK_ENV=development
    depends_on:
      - db
  localhost:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=univesp
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: