"""Rename endereco column to address

Revision ID: 094cb6f74ce0
Revises: a2f1762cbc94
Create Date: 2025-10-07 21:57:09.553718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '094cb6f74ce0'
down_revision = 'a2f1762cbc94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
